# Generated by Django 4.2.30 on 2026-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('dealer', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
                ('cars', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('initials', models.CharField(max_length=10)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.FloatField(default=0.0)),
                ('response', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specialties', models.JSONField(default=list)),
                ('hours', models.CharField(max_length=150)),
            ],
        ),
    ]
