# Generated by Django 4.2.30 on 2026-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
